name: present_unit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  intl: ^0.20.2
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.1
  http: ^1.2.2
  equatable: ^2.0.7
  email_validator: ^3.0.0
  local_auth: ^2.3.0
  flutter_svg: ^2.0.17
  get_storage: ^2.1.1
  csv: ^6.0.0
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  flutter_slidable: ^4.0.0
  url_launcher: ^6.3.1
  supabase_flutter: ^2.8.4
  syncfusion_flutter_pdfviewer: ^28.2.11
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/present-unit-logo.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
