// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAho_oAqnWakwANOrgV6eYks3ANzDn5kZE',
    appId: '1:92580548493:android:b649ab00e3cc91a2aef7c4',
    messagingSenderId: '92580548493',
    projectId: 'present-unit',
    storageBucket: 'present-unit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDPHVIlvZrFCgE1HG3K-i65bK8odumj6k',
    appId: '1:92580548493:ios:a1c8d48e59cc503aaef7c4',
    messagingSenderId: '92580548493',
    projectId: 'present-unit',
    storageBucket: 'present-unit.firebasestorage.app',
    iosBundleId: 'com.presentunit.presentUnit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDPHVIlvZrFCgE1HG3K-i65bK8odumj6k',
    appId: '1:92580548493:ios:a1c8d48e59cc503aaef7c4',
    messagingSenderId: '92580548493',
    projectId: 'present-unit',
    storageBucket: 'present-unit.firebasestorage.app',
    iosBundleId: 'com.presentunit.presentUnit',
  );
}
